export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_BACK_TO_PRODUCTS = "ADD_BACK_TO_PRODUCTS";
export const WISHLIST_TO_CART = "WISHLIST_TO_CART";
export const ITEM_QUANTITY_INCREASE = "ITEM_COUNTER_INCREASE";
export const ITEM_QUANTITY_DECREASE = "ITEM_COUNTER_DECREASE";
export const MOVE_TO_WISHLIST = "MOVE_TO_WISHLIST";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";


